version: '0.1'
services:
  web:
    image: "ellistheellice/websocket-pong"
    ports:
      - "80:8081"
    environment:
      - PORT=8081
  #db:
  #  image: "ellistheellice/websocket-pong-db"
  #  volumes:
  #    - /tmp/persdata:/var/lib/mysql
