services:
  web:
    image: "ellistheellice/websocket-pong"
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
  db:
    image: "mysql"
    volumes:
      - <your-folder>:/var/lib/mysql
      - ../init-db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=pong