version: '0.1'
services:
  web:
    image: "ellistheellice/websocket-pong"
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
  db:
    image: "mysql"
    volumes:
      - C:\Users\sengbers\Desktop\pong-db:/var/lib/mysql
